apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: piggymetrics
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
  - name: http
    port: 6000
    targetPort: 6000
