apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: hdxt25/piggymetrics-auth-service:2
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD

        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: NOTIFICATION_SERVICE_PASSWORD

        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: STATISTICS_SERVICE_PASSWORD

        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: ACCOUNT_SERVICE_PASSWORD

        # -----------------------------
        # MongoDB Connection (Important)
        # -----------------------------
        - na

