apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: hdxt25/piggymetrics-config:1
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD
        ports:
        - containerPort: 8888
