apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: hdxt25/piggymetrics-notification-service:2
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD

        # ---------- MongoDB Connection ----------
        - name: MONGODB_HOST
          value: "notification-mongodb.piggymetrics.svc.cluster.local"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "root"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD
        # -----------------------------------------

        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: NOTIFICATION_SERVICE_PASSWORD

        ports:
        - containerPort: 8000

