apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: hdxt25/piggymetrics-notification-service:1
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: NOTIFICATION_SERVICE_PASSWORD
        ports:
        - containerPort: 8000
