apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  namespace: piggymetrics
spec:
  type: ClusterIP
  selector:
    app: statistics-service
  ports:
  - name: http
    port: 7000
    targetPort: 7000
