apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-service
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
      - name: statistics-service
        image: hdxt25/piggymetrics-statistics-service:2
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD

        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD

        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: STATISTICS_SERVICE_PASSWORD

        # ------------------------
        # Added MongoDB connection details
        # ------------------------
        - name: MONGODB_HOST
          value: "statistics-mongodb.piggymetrics.svc.cluster.local"

        - name: MONGODB_PORT
          value: "27017"

        - name: MONGODB_USERNAME
          value: "root"

        ports:
        - containerPort: 7000
