apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-stream-service
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbine-stream-service
  template:
    metadata:
      labels:
        app: turbine-stream-service
    spec:
      containers:
      - name: turbine-stream-service
        image: hdxt25/piggymetrics-turbine-stream-service:0
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD
        ports:
        - containerPort: 8989