apiVersion: v1
kind: Service
metadata:
  name: turbine-stream-service
  namespace: piggymetrics
spec:
  type: ClusterIP
  selector:
    app: turbine-stream-service
  ports:
  - name: tcp
    port: 8989
    targetPort: 8989