apiVersion: v1
kind: Service
metadata:
  name: account-mongodb
  namespace: piggymetrics
spec:
  type: ClusterIP
  selector:
    app: account-mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017