apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
  namespace: piggymetrics
spec:
  type: ClusterIP
  selector:
    app: auth-mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017