apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
      - name: mongodb
        image: hdxt25/piggymetrics-mongodb:1
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: pvc-auth-mongodb
